version: '3.8'

services:
  # Backend service
  backend:
    image: dharanshneema/stock-sentiment:backend
    container_name: stock-sentiment-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - stock-sense-network

  # Frontend service
  frontend:
    image: dharanshneema/stock-sentiment:frontend
    container_name: stock-sentiment-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stock-sense-network

networks:
  stock-sense-network:
    driver: bridge
